### ISSUE TITLE
OS platforms is required and other Node.js refs

### ISSUE THREAD

**Issue by the-homeless-god** [OnedocLabs/react-print-pdf#5] opened 2024-02-29 07:42 UTC
<img width="927" alt="image" src="https://github.com/OnedocLabs/react-print-pdf/assets/32175240/f7e7fbd9-b2fe-48db-9644-c6b45f82b0d1">

<img width="568" alt="image" src="https://github.com/OnedocLabs/react-print-pdf/assets/32175240/8bd4fc64-3d59-4d64-a7c2-6a10b354808a">

Looks like `os.platform` is not available by default

```
❯ node --version
v20.6.1

❯ npm --version
np9.8.1
```

**Comment by the-homeless-god** [comment] 2024-02-29 08:23
Looks like a lot of Node.js references.

**Comment by the-homeless-god** [comment] 2024-02-29 12:18
Same situation for react-scripts just at the project built from scratch

<img width="775" alt="image" src="https://github.com/OnedocLabs/react-print-pdf/assets/32175240/c974725d-e396-44eb-be2f-3bcdbd4dc60f">

**Comment by the-homeless-god** [comment] 2024-02-29 13:02
Same for Next.js

It looks like the reason is tailwind

<img width="319" alt="image" src="https://github.com/OnedocLabs/react-print-pdf/assets/32175240/10c4b28c-f287-4b5b-bf50-a529e482c1ab">

<img width="652" alt="image" src="https://github.com/OnedocLabs/react-print-pdf/assets/32175240/5499b922-bc05-48d3-b000-40cd3bc9c9cd">

<img width="645" alt="image" src="https://github.com/OnedocLabs/react-print-pdf/assets/32175240/34560268-9b7c-47f0-aabd-0258c1cb7c03">

**Comment by Titou325** [comment] 2024-02-29 13:17
Hey @the-homeless-god, Tailwind support is server-side only so you may be encountering these issues as Tailwind parses a list of files to detect classes. However under our implementation we should be able to get going without scouting all files. I'll have a look

**Comment by eliasamaral** [comment] 2024-03-03 22:40
I face the same issue, and my web application doesn't use Tailwind. The error already appears upon import.

**Comment by Titou325** [comment] 2024-03-04 20:15
Hi @eliasamaral @the-homeless-god I am not able to reproduce this on my end. Would you have a sample repo or more repro steps on how you used the library so I can give a better look? Thanks!

**Comment by the-homeless-god** [comment] 2024-03-04 22:19
> Hi @eliasamaral @the-homeless-god I am not able to reproduce this on my end. Would you have a sample repo or more repro steps on how you used the library so I can give a better look? Thanks!

I've just created app via create-react-app, or next.js, or vite from scratch
I will create a sample repo for you tomorrow, but the most important thing is:

npx create-react-app
npm i react-print-pdf

and try to configure by guide and start an application. It will fail.

**Comment by Titou325** [comment] 2024-03-04 22:24
I would expect vite and create-react-app to fail as they are frontend only and we have an issue with [tsup](https://github.com/egoist/tsup/issues/1085) to bundle file system dependencies without a file system. Next should work though.

I'd be glad to take a look at the Next.js example. We use Next as our own backend and it seems to work for us as long as the docs are generated in API or pages rather than client components.

Thank you very much for your help!

**Comment by eliasamaral** [comment] 2024-03-07 16:50
Just creating a clean project in Vite, without any added dependencies, is already enough to encounter the error. Take a look at this repo:  https://github.com/eliasamaral/Onedoc_issues_-5/tree/main/vite-project

**Comment by Titou325** [comment] 2024-03-10 02:44
Hey guys!

We dug deeper into this and because of a complex behavior of Tailwind when used with PostCSS, we can't port the Tailwind handling to the client as of now.

Given that the rest of `react-print-pdf` does not rely on Tailwind and can be ported to the client, we have created a sub-import at `@onedoc/react-print-pdf/client` that allows import of all client-compatible components without overlap. In the near future we will split each component to a separate bundle to prevent this from happening.

The docs have been updated to show the support for each component (i.e. https://react.onedoclabs.com/components/tailwind)

I will close this issue and create a new one for Tailwind specifically.

Thanks!

**Closed by Titou325** 2024-03-10 02:44 UTC
Labels: bug
